# Generated by Django 5.1.4 on 2025-02-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teafirst', '0005_order_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'wait'), ('completed', 'success')], default='waiting', max_length=20),
        ),
    ]
